# Generated by Django 3.2.7 on 2021-09-22 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('address_line1', models.CharField(max_length=50)),
                ('address_line2', models.CharField(blank=True, max_length=50)),
                ('address_line3', models.CharField(blank=True, max_length=50)),
                ('address_city', models.CharField(max_length=50)),
                ('address_county', models.CharField(max_length=50)),
                ('address_post_code', models.CharField(max_length=50)),
                ('address_country', models.CharField(max_length=50)),
                ('alerts', models.BooleanField(default=False)),
                ('newsletter', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='media')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'InfoUsers',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.FloatField(default=0.0)),
                ('interest_rate', models.FloatField(default=0.0)),
                ('duration', models.IntegerField(default=0)),
                ('monthly_payment', models.FloatField(default=0.0, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_purpose', models.CharField(choices=[('Home improvements', 'Home improvements'), ('Debt consolidation', 'Debt consolidation'), ('Car purchase', 'Car purchase'), ('Holiday', 'Holiday'), ('Wedding', 'Wedding'), ('Buy property', 'Buy property'), ('Buy land', 'Buy land'), ('Buy property with land', 'Buy property with land'), ('Other', 'Other')], default='', max_length=100)),
                ('loan_amount', models.FloatField(default=0)),
                ('loan_term', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=100)),
                ('interest_rate', models.FloatField(default=0.0)),
                ('date_of_birth', models.DateField(max_length=10)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Divorced', 'Divorced'), ('Single', 'Single'), ('Co-habituating', 'Co-habituating'), ('Widowed', 'Widowed'), ('Civil Partnership', 'Civil Partnership'), ('Separated', 'Separated')], default='', max_length=100)),
                ('children', models.IntegerField(blank=True, default=0)),
                ('residential_status', models.CharField(choices=[('Owner', 'Owner'), ('Owner with mortgage', 'Owner with mortgage'), ('Tenant', 'Tenant'), ('Council tenant', 'Council tenant'), ('Employer accommodation', 'Employer accommodation'), ('Living with family or friends', 'Living with family or friends')], default='', max_length=100)),
                ('residence_duration', models.IntegerField(default=0)),
                ('employment_status', models.CharField(choices=[('Full time', 'Full time'), ('Self employed', 'Self employed'), ('Benefits', 'Benefits'), ('Part time', 'Part time'), ('Temporary employment', 'Temporary employment'), ('Student', 'Student'), ('Retired', 'Retired'), ('Contractor', 'Contractor'), ('Zero hour contract', 'Zero hour contract'), ('Trainee', 'Trainee')], default='', max_length=100)),
                ('monthly_salary', models.FloatField(default=0)),
                ('monthly_expenses', models.FloatField(default=0)),
                ('monthly_rent', models.FloatField(default=0)),
                ('bankrupted', models.BooleanField(default=False)),
                ('monthly_payment', models.FloatField(default=0.0, null=True)),
                ('fees', models.FloatField(default=0.0, null=True)),
                ('loan_total', models.FloatField(default=0.0, null=True)),
                ('take_home', models.FloatField(default=0.0, null=True)),
                ('loan_documentation', models.FileField(blank=True, null=True, upload_to='media')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.topic')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_message_subject', models.TextField(max_length=200)),
                ('customer_message', models.TextField(max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
