# Generated by Django 3.2.6 on 2021-09-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_topic_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('contact_number', models.CharField(max_length=50)),
                ('address_line1', models.CharField(max_length=50)),
                ('address_line2', models.CharField(max_length=50)),
                ('address_line3', models.CharField(max_length=50)),
                ('address_city', models.CharField(max_length=50)),
                ('address_post_code', models.CharField(max_length=50)),
                ('address_country', models.CharField(max_length=50)),
                ('alerts', models.BooleanField(default=False)),
                ('newsletter_selection', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'InfoUsers',
            },
        ),
    ]
