# Generated by Django 3.2.6 on 2021-09-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_userinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='address_county',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='address_line2',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='address_line3',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
