# Generated by Django 3.2.6 on 2021-09-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_auto_20210904_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='address_line2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='address_line3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='contact_number',
            field=models.IntegerField(default=0),
        ),
    ]
