# Generated by Django 3.2.6 on 2021-09-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0012_auto_20210907_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='owner',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
