# Generated by Django 3.2.7 on 2021-09-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0014_alter_userinformation_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='profile_picture',
            field=models.ImageField(upload_to='my_space/<int:auth_user_id>/media'),
        ),
    ]
