# Generated by Django 3.2.7 on 2021-09-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0018_alter_userinformation_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='newsletter_selection',
            new_name='newsletter',
        ),
    ]
