# Generated by Django 3.2.7 on 2021-09-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0019_rename_newsletter_selection_userinformation_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
