# Generated by Django 3.2.7 on 2021-09-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0028_loanapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='employment_status',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Self employed', 'Self employed'), ('Benefits', 'Benefits'), ('Part time', 'Part time'), ('Temporary employment', 'Temporary employment'), ('Student', 'Student'), ('Retired', 'Retired'), ('Contractor', 'Contractor'), ('Zero hour contract', 'Zero hour contract'), ('Trainee', 'Trainee')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_purpose',
            field=models.CharField(choices=[('Home improvements', 'Home improvements'), ('Debt consolidation', 'Debt consolidation'), ('Car purchase', 'Car purchase'), ('Holiday', 'Holiday'), ('Wedding', 'Wedding'), ('Buy property', 'Buy property'), ('Buy land', 'Buy land'), ('Buy property with land', 'Buy property with land'), ('Other', 'Other')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_term',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Divorced', 'Divorced'), ('Single', 'Single'), ('Co-habituating', 'Co-habituating'), ('Widowed', 'Widowed'), ('Civil Partnership', 'Civil Partnership'), ('Separated', 'Separated')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='residential_status',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Owner with mortgage', 'Owner with mortgage'), ('Tenant', 'Tenant'), ('Council tenant', 'Council tenant'), ('Employer accommodation', 'Employer accommodation'), ('Living with family or friends', 'Living with family or friends')], default='', max_length=100),
        ),
    ]
