# Generated by Django 3.2.7 on 2021-09-19 00:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0034_auto_20210919_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='children',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='GBP', max_digits=11, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_expenses',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='GBP', max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_rent',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='GBP', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_salary',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='GBP', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
