# Generated by Django 3.2.7 on 2021-09-19 10:10

from decimal import Decimal
import django.core.validators
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0035_auto_20210919_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='GBP', max_digits=11, validators=[djmoney.models.validators.MinMoneyValidator(djmoney.money.Money(0.01, 'GBP'))]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_expenses',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='GBP', max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_rent',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='GBP', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_salary',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='GBP', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
