# Generated by Django 3.2.7 on 2021-09-19 10:29

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0041_alter_loanapplication_monthly_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='children',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='GBP', max_digits=11),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_expenses',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='GBP', max_digits=11),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_rent',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='GBP', max_digits=11),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_salary',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='GBP', max_digits=11),
        ),
    ]
