# Generated by Django 3.2.7 on 2021-09-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0042_auto_20210919_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.FloatField(default=0.1)),
                ('interest_rate', models.FloatField(default=0.1)),
                ('duration', models.IntegerField(default=1)),
            ],
        ),
    ]
