# Generated by Django 3.2.7 on 2021-09-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0044_loancalculation_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancalculation',
            name='monthly_payment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loancalculation',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loancalculation',
            name='interest_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loancalculation',
            name='principal',
            field=models.FloatField(default=0.0),
        ),
    ]
