# Generated by Django 3.2.7 on 2021-09-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0045_auto_20210919_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loancalculation',
            name='monthly_payment',
        ),
    ]
