# Generated by Django 3.2.7 on 2021-09-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0046_remove_loancalculation_monthly_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancalculation',
            name='monthly_payment',
            field=models.FloatField(default=0.0),
        ),
    ]
