# Generated by Django 3.2.7 on 2021-09-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0047_loancalculation_monthly_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancalculation',
            name='monthly_payment',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
