# Generated by Django 3.2.7 on 2021-09-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0048_alter_loancalculation_monthly_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
