# Generated by Django 3.2.7 on 2021-09-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0050_loanapplication_monthly_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='fees',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_total',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='take_home',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
