# Generated by Django 3.2.7 on 2021-09-21 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0053_auto_20210922_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='principal',
        ),
    ]
