# Generated by Django 3.2.7 on 2021-09-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0054_remove_loanapplication_principal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='loan_amount_currency',
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
