# Generated by Django 3.2.7 on 2021-09-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0057_auto_20210922_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='loan_amount_currency',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='monthly_expenses_currency',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='monthly_rent_currency',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='monthly_salary_currency',
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_expenses',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_rent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_salary',
            field=models.FloatField(default=0.0),
        ),
    ]
